asset_manager/api/urls.py
from rest_framework.routers import SimpleRouter
from . import views
from file_manager import models

router = SimpleRouter()

router.register(
	"answers/collection/(?P<collection_id>\d+)/question/(?P<question_id>\d+)",
	views.AnswerPerCollectionAndQuestionViewSet,
	'answer-collection-question'
)
router.register(
	"asset/answer/(?P<answer_id>\d+)",
	views.AssetPerAnswerViewSet,
	'asset-answer'
)
router.register(
	"assets/collection/(?P<id>\d+)",
	views.AssetPerCollectionViewSet,
	'asset-collection'
	)
router.register(
	"assets/tag/(?P<id>\d+)",
	views.AssetPerTagViewSet,
	'asset-tag'
	)
router.register(
	"assets/collection/(?P<collection_id>\d+)/tag/(?P<tag_id>\d+)",
	views.AssetPerCollectionAndTagViewSet,
	'asset-collection-tag')
router.register(
	"assets/collection/(?P<collection_id>\d+)/tag-group/(?P<tag_group_id>\d+)",
	views.AssetPerCollectionAndTagGroupViewSet,
	'asset-collection-tag-group'
)
router.register(
	"assets/collection/(?P<collection_id>\d+)/location/(?P<location_id>\d+)",
	views.AssetPerCollectionAndLocationViewSet,
	'asset-collection-location'
),
router.register(
	"assets/collection/(?P<collection_id>\d+)/learner-journey/(?P<learner_journey_id>\d+)",
	views.AssetPerCollectionAndLearnerJourneyViewSet,
	'asset-collection-learner-journey'
),
router.register(
	"chapters/collection/(?P<collection_id>\d+)/learner-journey/(?P<learner_journey_id>\d+)",
	views.ChapterPerCollectionAndLearnerJourneyViewSet,
	'chapter-collection-learner-journey'
),
router.register(
	"chapter-ids/collection/(?P<collection_id>\d+)/learner-journey/(?P<learner_journey_id>\d+)",
	views.ChapterIdsPerCollectionAndLearnerJourneyViewSet,
	'chapter-ids-collection-learner-journey'
),
# router.register(
# 	"chapters/collection/(?P<collection_id>\d+)/learner-journey/(?P<learner_journey_id>\d+)/chapter/(?P<chapter_num>\d+)",
# 	views.ChapterPlusAssetViewSet,
# 	'chapter-plus-asset'
# )
router.register("answers", views.AnswerViewSet)
router.register("assets", views.AssetViewSet)
router.register("chapters", views.ChapterViewSet)
router.register("collections", views.CollectionViewSet)
router.register("contributors", views.ContributorViewSet)
router.register("countries", views.CountryTagViewSet)
router.register("learner-journeys", views.LearnerJourneyViewSet)
router.register("questions", views.QuestionViewSet)
router.register("tags", views.TagViewSet)
router.register("tag-groups", views.TagGroupViewSet)

urlpatterns = router.urls

asset_manager/asset_manager/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from rest_framework_jwt.views import obtain_jwt_token

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(('api.urls', 'api'), namespace='api')),
    url(r'^jwt-auth/', obtain_jwt_token, name='auth'),
    url(r'^', include(('user_interface.urls', 'user_interface'), namespace='user_interface')),
]

asset_manager/user_interface/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^topic/(?P<topic_id>\d+)$', views.topic, name='topic'),
    url(r'^asset/(?P<asset_id>\d+)$', views.asset, name='asset'),
    url(r'^search$', views.search, name='search'),
    url(r'data/$', views.data, name='data'),
]

asset_manager/file_manager/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models

from ckeditor.fields import RichTextField
from model_utils import FieldTracker

from . import s3_utils
from . import strings

import mimetypes

import logging
logging.basicConfig(
    filename=settings.LOGFILE,
    level=logging.INFO,
    format=' %(asctime)s - %(levelname)s - %(message)s'
    )
# logging.disable(logging.CRITICAL)

# Create your models here.
class S3_Object(models.Model):
    name = models.CharField(max_length=200)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


# ------------ Folders ------------ #

class Folder(S3_Object):
    parent = models.ForeignKey('self', blank=True, null=True, on_delete=models.CASCADE)
    tracker = FieldTracker()

    def __str__(self):
        path = self.get_path()
        if path.startswith(settings.MEDIAFILES_LOCATION + '/'):
            path = path[6:]
        return path

    def get_path(self):
        """
        Returns an up to date Folder path based on its location in the Django \
        model.
        """
        if not self.parent:
            return settings.MEDIAFILES_LOCATION + '/' + self.name
        else:
            return self.parent.get_path() + '/' + self.name

    def get_files(self):
        return self.file_set.all()

    def get_all_ancestor_folders(self):
        """
        Returns a list of all the ancestors of a given folder, including the folder itself
        """
        if not self.parent:
            return [self]
        else:
            ancestors = self.parent.get_all_ancestor_folders()
            ancestors.append(self)
            return ancestors

    def is_new_parent_valid(self, new_parent):
        """
        Returns True if the new_parent Folder is a valid parent for this Folder,
        otherwise returns False
        """
        new_parent_ancestors = new_parent.get_all_ancestor_folders()
        if self in new_parent_ancestors:
            return False
        return True

# ------------ Tags ------------ #

class TagGroup(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name', )

class Tag(models.Model):
    name = models.CharField(max_length=64)
    group = models.ForeignKey(TagGroup, on_delete=models.CASCADE)
    deprecated = models.BooleanField(default=False)

    def __str__(self):
        return self.group.name.title() + ' | ' + self.name

    class Meta:
        ordering = ('name', )

class ContinentTagGroup(models.Model):
    name = models.CharField(max_length=64)
    code = models.CharField(max_length=2, null=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name', )

class CountryTag(models.Model):
    name = models.CharField(max_length=64)
    display_name = models.CharField(max_length=32, blank=True)
    code = models.CharField(max_length=3, null=True)
    continent = models.ForeignKey(ContinentTagGroup, on_delete=models.CASCADE)

    def __str__(self):
        return self.continent.name.title() + ' | ' + self.name

    class Meta:
        ordering = ('name', )

# ------------ Contributor ------------ #

class Contributor(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name

# ------------ Collection ------------ #

class Collection(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name

# ------------ LearnerJourney ------------ #

class LearnerJourney(models.Model):

    def get_s3_key(self, filename):
        return 'smf-prototype/thumbnails/' + filename

    name = models.CharField(max_length=64)
    description = models.TextField(blank=True, null=True, max_length=1024)
    duration = models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Duration (hours)')
    thumbnail = models.ImageField(upload_to=get_s3_key, blank=True)

    def __str__(self):
        return self.name

# ------------ Question ------------ #

class Question(models.Model):

    def get_s3_key(self, filename):
        return 'smf-prototype/thumbnails/' + filename

    name = models.CharField(max_length=64)
    description = models.TextField(blank=True, null=True, max_length=1024)
    intro_title = models.TextField(blank=True, null=True, max_length=64)
    intro_text = models.TextField(blank=True, null=True, max_length=512)
    quote = models.TextField(blank=True, null=True, max_length=256)
    quote_source = models.TextField(blank=True, null=True, max_length=64)
    thumbnail = models.ImageField(upload_to=get_s3_key, blank=True)

    def __str__(self):
        return self.name

# ------------ Assets ------------ #

class Asset(S3_Object):

    def get_s3_key(self, filename):
        return str(self.parent.id) + '/' + filename

    name = models.CharField(max_length=64, help_text=strings.ASSET_NAME_HELPER)
    parent = models.ForeignKey(Folder, on_delete=models.CASCADE, help_text=strings.ASSET_PARENT_HELPER)
    file = models.FileField(upload_to=get_s3_key, blank=True, help_text=strings.ASSET_FILE_NAME_HELPER)
    link = models.URLField(blank=True)

    tags = models.ManyToManyField(Tag, blank=True)
    locations = models.ManyToManyField(CountryTag, blank=True)
    contributors = models.ManyToManyField(Contributor, blank=True)
    collections = models.ManyToManyField(Collection, blank=True)

    description = models.TextField(blank=True)
    duration = models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Duration (mins)')
    creation_date = models.DateField(blank=True, null=True)
    copyright_info = models.TextField(blank=True)
    enabled = models.BooleanField(default=True)

    PROTOTYPE = 'PT'
    START_UP = 'SU'
    ACTIVE = 'AC'
    ON_MARKET = 'OM'
    PROJECT = 'PR'
    RESEARCH = 'RS'
    COMPLETE = 'CM'
    DISCONTINUED = 'DS'
    STATUS_CHOICES = (
        (PROTOTYPE, 'Prototype'),
        (START_UP, 'Start Up'),
        (ACTIVE, 'Active'),
        (ON_MARKET, 'On Market'),
        (PROJECT, 'Project'),
        (RESEARCH, 'Research'),
        (COMPLETE, 'Complete'),
        (DISCONTINUED, 'Discontinued'),
    )
    status = models.CharField(
        max_length=2,
        choices=STATUS_CHOICES,
        blank=True,
        verbose_name='Status (Case Studies only)'
    )

    CASE_STUDY = 'CS'
    CO_PROJECT = 'CP'
    PAPER = 'PA'
    REPORT = 'RT'
    INFOGRAPHIC = 'IG'
    TEACHING_LEARNING = 'TL'
    OTHER = 'OT'

    TYPE_CHOICES = (
        (CASE_STUDY, 'Case study'),
        (CO_PROJECT, 'Co.Project'),
        (PAPER, 'Paper'),
        (REPORT, 'Report'),
        (INFOGRAPHIC, 'Infographic'),
        (TEACHING_LEARNING, 'Teaching & learning resource'),
        (OTHER, 'Other')
    )
    type_field = models.CharField(
        default=OTHER,
        max_length=2,
        choices = TYPE_CHOICES,
        verbose_name='Content Type'
    )

    IMAGE = 'IM'
    VIDEO = 'VI'
    PRESENTATION = 'PR'
    LINK = 'LN'
    AUDIO = 'AU'
    DOCUMENT = 'DO'

    FORMAT_CHOICES = (
        (IMAGE, 'Image'),
        (VIDEO, 'Video'),
        (PRESENTATION, 'Presentation'),
        (LINK, 'Web link'),
        (AUDIO, 'Audio'),
        (DOCUMENT, 'Document'),
        (OTHER, 'Other')
    )
    format = models.CharField(
        max_length=2,
        choices = FORMAT_CHOICES,
        default = OTHER,
        verbose_name='Format'
    )

    filetype = models.CharField(max_length=128, null=True)
    uploaded_at = models.DateTimeField(null=True)
    last_edit_at = models.DateTimeField(null=True)

    uploaded_by = models.ForeignKey(User, on_delete=models.PROTECT, null=True, related_name='asset_uploaded_by')
    last_edit_by = models.ForeignKey(User, on_delete=models.PROTECT, null=True, related_name='asset_last_edit_by')
    owner = models.ForeignKey(User, on_delete=models.PROTECT, blank=True, null=True)

    tracker = FieldTracker()

    def __str__(self):
        return self.parent.get_path() + '/' + self.name

    def save(self, *args, **kwargs):

        # if first save
        if not self.id:
            self.update_filetype()

        # if a new file is uploaded, the filename will be updated whether or not the parent has changed
        elif self.tracker.has_changed('file'):
            old_s3_key = settings.MEDIAFILES_LOCATION + '/' + self.tracker.previous('file').name
            s3_utils.delete_s3_object(old_s3_key)
            # update filetype
            self.update_filetype()

        # but if a file is already attached, and the parent is changed, this must be handled manually
        elif self.file and self.tracker.has_changed('parent_id'):
            old_file_name = self.file.name
            self.file.name = str(self.parent.id) + '/' + self.get_filename()
            logging.info('Filename changed from {0} to {1}'.format(old_file_name, self.file.name))

            media_dir = settings.MEDIAFILES_LOCATION

            s3_utils.update_s3_key(media_dir + '/' + old_file_name, media_dir + '/' + self.file.name)

        super(Asset, self).save(*args, **kwargs)

    def get_path(self):
        return self.parent.get_path() + '/' + self.name
    get_path.short_description = 'Full Path'

    def get_filename(self):
        """
        Asset.file.name contains the full filepath, relative to MEDIAFILES_LOCATION ie 'parent_id/filename'
        To get just the filename, we split the string from the right, once, on first '/'
        """
        filename = self.file.name
        if '/' in filename:
            return filename.rsplit('/',1)[1]
        return filename

    def update_filetype(self):
        """
        Automatically update filetype field based on file field
        """
        if self.file:
            self.filetype = mimetypes.guess_type(self.get_filename())[0]
        else:
            self.filetype = ''

# ------------ Asset-LearnerJourney Through table (Chapter) ------------ #

asset_manager/user_interface/models.py
from django.db import models

# Create your models here.

asset_manager/user_interface/views.py
from django.shortcuts import render
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.contrib.postgres.aggregates import StringAgg
from file_manager.models import TagGroup, Tag, Asset
from django.conf import settings

formatToIcon = {
	'IM': 'image',
	'VI': 'video',
	'PR': 'file-powerpoint',
	'LN': 'link',
	'AU': 'headphones',
	'DO': 'file',
	'OT': 'file'
}

# very brittle: we should consider creating a field on TagGroup to hold the svg file
tagGroupToIcon = {
	'BIOCYCLE': 'bug',
	'BUILT ENVIRONMENT': 'building',
	'BUSINESS': 'briefcase',
	'DESIGN': 'brush',
	'ECONOMICS': 'pie-chart',
	'EDUCATION (LEARNING)': 'map',
	'ENERGY': 'lightning',
	'FINANCE & LEGAL': 'balance',
	'GOVERNMENT': 'bank',
	'MANUFACTURING & ENGINEERING': 'idea',
	'MATERIALS': 'lab',
	'TECHNICAL CYCLE': 'gears',
	'TECHNOLOGY': 'touch'
}

# Create your views here.
def index(request):
	topics = TagGroup.objects.all()
	context = { 
		'topics': topics,
		'tagGroupToIcon': tagGroupToIcon
	}
	return render(request, 'user_interface/index.html', context)

def topic(request, topic_id):
	thisTopic = TagGroup.objects.get(id=topic_id)
	tags = Tag.objects.filter(group__id=topic_id)
	assets = Asset.objects.filter(tags__in=tags).distinct()
	typeChoices = { k:v for (k,v) in Asset.TYPE_CHOICES }

	context = { 
		'topic': thisTopic,
		'assets': assets,
		'formatToIcon': formatToIcon,
		'typeChoices': typeChoices
	}
	return render(request, 'user_interface/topic.html', context)

def asset(request, asset_id):
	item = Asset.objects.get(id=asset_id)
	filename = ('https://' + settings.AWS_STORAGE_BUCKET_NAME
		+ '.s3.amazonaws.com/media/' + item.file.name)
	topicGroup = request.GET.get('t', '')
	icon = formatToIcon.get(item.format, 'OT')
	context = { 
		'asset': item,
		'filename': filename,
		'topicGroup': topicGroup,
		'icon': icon
	}
	return render(request, 'user_interface/asset.html', context)

def search(request):
	searchTerm = request.GET.get('q', '')

	if searchTerm:
		queries = [SearchQuery(term) for term in searchTerm.split(' ')]
		query = queries.pop()
		for item in queries:
			query &= item

		vector = (
			SearchVector('name', weight='A') +
			SearchVector('description', weight='A') +
			SearchVector(StringAgg('tags__name', delimiter=' '), weight='B') +
			SearchVector(StringAgg('locations__name', delimiter=' '), weight='B') +
			SearchVector(StringAgg('contributors__name', delimiter=' '), weight='B')
		)
		
		assets = Asset.objects.annotate(document=vector, rank=SearchRank(vector, query))\
					  .filter(document=query).order_by('type_field', '-rank')
	else:
		assets = None
	typeChoices = { k:v for (k,v) in Asset.TYPE_CHOICES }

	context = { 
		'searchTerm': searchTerm,
		'assets': assets,
		'formatToIcon': formatToIcon,
		'typeChoices': typeChoices
	}

	return render(request, 'user_interface/search.html', context)

def data(request):
   return render(request, 'data.html')

asset_manager/user_interface/templates/user_interface/asset.html
{% extends 'user_interface/base.html' %}

{% block title %}
	{{ block.super }} - {{ asset.name }}
{% endblock %}

{% block content %}
<section class="hero is-medium">
  <div class="hero-body dam-hero dam-asset-hero">
    <div class="container">
      <div class="">
        <a href="{% if topicGroup %}{% url 'user_interface:topic' topicGroup %}{% else %}/{% endif %}"
           class="has-text-grey">
          < Back
        </a>
      </div>
      <br>
      <div class="dam-container-narrow">
        <div class="content">
          <p>
            <span class="icon is-medium dam-icon-border dam-is-circle">
              <i class="fas fa-{{ icon }}"></i>
            </span>
            <span class="dam-margin-left has-text-primary">{{ asset.get_format_display }}</span>
            <span class="dam-margin-left-large">{{ asset.get_type_field_display|lower|capfirst }}</span>
          </p>
          <h1 class="dam-title has-text-weight-bold is-size-3-touch is-size-1-desktop">
            {{ asset.name }}
          </h1>
        
          <p class="has-text-grey dam-margin-bottom">Uploaded at {{ asset.uploaded_at|date:"jS F, Y" }}</p>
          <p>
            {% if asset.link %}
              <a href="{{ asset.link }}" class="button is-primary dam-button" target="_blank">
                GO TO WEBSITE
              </a>
              <a href="mailto:?to=&body={{ asset.link }}&subject={{ asset.name }}"
                class="button is-primary dam-button">
                SHARE
              </a>
            {% elif asset.file %}
              <a href="{{ filename }}"
                class="button is-primary dam-button"
                target="_blank">
                DOWNLOAD
              </a>
              <a href="mailto:?to=&body={{ filename }}&subject={{ asset.name }}"
                class="button is-primary dam-button">
                SHARE
              </a>
            {% else %}
              File/link coming soon...
            {% endif %}
          </p>
        </div>
      </div>
    </div>
  </div>
</section>

{% if asset.description %}
  <section class="section">
    <div class="container dam-container-narrow">
      <div class="content">
        <p>{{ asset.description }}</p>
      </div>
    </div>
  </section>
{% endif %}

{% if asset.contributors.all|length %}
  <section class="section">
    <div class="container dam-container-narrow">
      <div class="content">
        <p>Collaborators</p>
      </div>
      <div class="columns is-multiline">
        {% for contributor in asset.contributors.all %}
        <div class="column is-half">
          <article class="media">
            <figure class="media-left">
                <span class="icon is-medium dam-is-circle dam-icon-full">
                  <i class="fas fa-user"></i>
                </span>
            </figure>
            <div class="media-content">
              <div class="content">
                {{ contributor.name }}
              </div>
            </div>
          </article>
        </div>
        {% endfor %}
      </div>
    </div>
  </section>
{% endif %}

{% if asset.tags.all|length %}
  <section class="section">
    <div class="container dam-container-narrow">
      <div class="content">
        <p>This is about...</p>
      </div>
      <div class="tags">
        {% for tag in asset.tags.all %}
        <span class="tag is-white is-medium dam-tag">{{ tag.name }}</span>
        {% endfor %}
      </div>
	  </div>
  </section>
{% endif %}
{% endblock %}

asset_manager/user_interface/templates/user_interface/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}EMF: Digital Asset Manager{% endblock %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://use.typekit.net/qvs1foo.css">
	<script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
	<link rel="apple-touch-icon" sizes="180x180" href="{% static 'user_interface/icons/apple-touch-icon.png' %}">
	<link rel="icon" type="image/png" sizes="32x32" href="{% static 'user_interface/icons/favicon-32x32.png' %}">
	<link rel="icon" type="image/png" sizes="16x16" href="{% static 'user_interface/icons/favicon-16x16.png' %}">
	<link rel="manifest" href="{% static 'user_interface/icons/site.webmanifest' %}">
	<link rel="mask-icon" href="{% static 'user_interface/icons/safari-pinned-tab.svg' %}" color="#3e4db9">
	<meta name="msapplication-TileColor" content="#3e4db9">
	<meta name="theme-color" content="#3e4db9">
  <link rel="stylesheet" type="text/css" href="{% static 'user_interface/css/main.css' %}" />
  <script src="https://cdn.jsdelivr.net/npm/vue@2.5.16/dist/vue.js"></script>
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-12790826-17"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'UA-12790826-17');
	</script>
</head>
<body>
  <div id="app">
    <nav class="dam-shadow-bottom" role="navigation" aria-label="main navigation">
      <div class="navbar-brand dam-nav">
        <a class="navbar-item dam-nav-link" href="/">
          <img src="{% static 'user_interface/images/emf-logo.png' %}" alt="Ellen MacArthur Foundation resources">
        </a>
        <div class="navbar-item">
          <strong>RESOURCES</strong>
        </div>
        <a href="{% url 'user_interface:search' %}" 
           class="navbar-item dam-nav-link"
           @click="toggleSearch">
          <span class="icon">
            <i class="fas fa-lg fa-search"></i>
          </span>
        </a>
      </div>
    </nav>
    <div class="modal" :class="{ 'is-active': showSearch }">
      <div class="modal-background"></div>
      <div class="modal-content">
        <div class="box">
          <form action="{% url 'user_interface:search' %}">
              <div class="field has-addons">
                <div class="control is-expanded">
                  <input class="input is-large" name="q" type="text" placeholder="Find a resource">
                </div>
                <div class="control">
                  <button type="submit" class="button is-large is-primary">
                    <span class="icon">
                      <i class="fas fa-search"></i>
                    </span>
                  </button>
                </div>
              </div>
            </form>
        </div>
      </div>
      <button class="modal-close is-large" @click="toggleSearch" aria-label="close"></button>
    </div>
    {% block content %}{% endblock %}
    <footer class="section is-white">
      <div class="container">
        <p class="has-text-grey-light is-size-7">
          Charity Registration No.: 1130306,
          OSCR Registration No.: SC043120,
          Company No.: 6897785
          <br />
          © Copyright 2017 Ellen MacArthur Foundation.
            All Rights Reserved
        </p>
      </div>
    </footer>
  </div>
  <script src="{% static 'user_interface/js/main.js' %}"></script>
</body>
</html>

asset_manager/user_interface/templates/user_interface/search.html
{% extends 'user_interface/base.html' %}

{% load custom_filters %}

{% block content %}
<section class="hero is-medium">
	<div class="hero-body dam-hero">
		<div class="container">
      <h1 class="has-text-weight-bold is-size-3-touch is-size-1-desktop">Search</h1>
      <form action="{% url 'user_interface:search' %}">
        <div class="field has-addons">
          <div class="control">
            <input class="input" name="q" value="{{ searchTerm }}" type="text" placeholder="Find a resource">
          </div>
          <div class="control">
            <button type="submit" class="button is-primary">
              <span class="icon">
                <i class="fas fa-search"></i>
              </span>
            </button>
          </div>
        </div>
      </form>
		</div>
	</div>
</section>

<section class="section">
  <div class="container">
    {% if assets %}
      {% regroup assets by type_field as assets_by_type %}
      {% for type in assets_by_type %}
        <div class="dam-padding">
          <h2 class="title is-6 has-text-weight-normal">
            {{ typeChoices|get_item:type.grouper|lower|capfirst }}
          </h2>
        </div>
        <div class="columns is-multiline">
          {% for asset in type.list %}
            <div class="column is-half is-one-third-desktop">
              <article class="media dam-media">
                <figure class="media-left dam-media-left">
                  <span class="icon is-medium dam-icon-border dam-is-circle">
                    <i class="fas fa-{{ formatToIcon|get_item:asset.format }}"></i>
                  </span>
                  <figcaption class="dam-format-text dam-icon is-size-7 has-text-primary has-text-centered is-hidden-touch">
                    {{ asset.get_format_display }}
                  </figcaption>
                </figure>
                <div class="media-content">
                  <div class="content">
                    <a href="{% url 'user_interface:asset' asset.id %}?t={{ topic.id }}">
                      <h3 class="is-size-6 has-text-weight-bold">{{ asset.name }}</h3>
                    </a>
                  </div>
                </div>
              </article>
            </div>
            {% endfor %}
          </div>
        {% endfor %}
      {% else %}
        <p>No results found for <strong>{{ searchTerm }}</strong>.</p>
      {% endif %}
  </div>
</section>
{% endblock %}

asset_manager/user_interface/templates/user_interface/topic.html
{% extends 'user_interface/base.html' %}

{% load custom_filters %}

{% block title %}
	{{ block.super }} - {{ topic.name |lower|capfirst}}
{% endblock %}

{% block content %}
<section class="hero is-medium">
  <div class="hero-body dam-hero">
    <div class="container">
      <div class="dam-back has-text-grey">
        <a href="/">< Back</a>
      </div>
      <h1 class="has-text-weight-bold is-size-3-touch is-size-1-desktop">
        {{ topic.name|lower|capfirst }}
      </h1>
    </div>
	</div>
</section>

{% regroup assets|dictsort:'type_field' by type_field as assets_by_type %}

<section class="section">
  <div class="container">
    {% for type in assets_by_type %}
      <div class="dam-padding">
        <h2 class="title is-6 has-text-weight-normal">
          {{ typeChoices|get_item:type.grouper|lower|capfirst }}
        </h2>
      </div>
      <div class="columns is-multiline">
        {% for asset in type.list %}
          <div class="column is-half is-one-third-desktop">
            <article class="media dam-media">
              <figure class="media-left dam-media-left">
                <span class="icon is-medium dam-icon-border dam-is-circle">
                  <i class="fas fa-{{ formatToIcon|get_item:asset.format }}"></i>
                </span>
                <figcaption class="dam-format-text dam-icon is-size-7 has-text-primary has-text-centered is-hidden-touch">
                  {{ asset.get_format_display }}
                </figcaption>
              </figure>
              <div class="media-content">
                <div class="content">
                  <a href="{% url 'user_interface:asset' asset.id %}?t={{ topic.id }}">
                    <h3 class="is-size-6 has-text-weight-bold">{{ asset.name }}</h3>
                  </a>
                </div>
              </div>
            </article>
          </div>
          {% endfor %}
        </div>
      {% endfor %}
  </div>
</section>
{% endblock %}